# Multi-stage build for React + Node.js app
FROM node:18-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package files
COPY package*.json ./

# Install dependencies
RUN npm ci --only=production=false

# Copy source files
COPY . .

# Accept build arguments for REACT_APP_* variables
# These are injected by Railway during build time
ARG REACT_APP_PAYPAL_CLIENT_ID
ARG REACT_APP_PAYPAL_CLIENT_ID_SANDBOX
ARG REACT_APP_PAYPAL_ENVIRONMENT
ARG REACT_APP_PAYPAL_CURRENCY
ARG REACT_APP_PAYPAL_INTENT
ARG REACT_APP_EMAILJS_SERVICE_ID
ARG REACT_APP_EMAILJS_TEMPLATE_ID
ARG REACT_APP_EMAILJS_PUBLIC_KEY
ARG REACT_APP_TRANSLATE_API_KEY
ARG REACT_APP_STRIPE_PUBLISHABLE_KEY
ARG REACT_APP_FIREBASE_API_KEY
ARG REACT_APP_FIREBASE_AUTH_DOMAIN
ARG REACT_APP_FIREBASE_PROJECT_ID
ARG REACT_APP_FIREBASE_STORAGE_BUCKET
ARG REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ARG REACT_APP_FIREBASE_APP_ID
ARG REACT_APP_SHIPPO_API_TOKEN

# Convert ARG to ENV so they're available during npm run build
ENV REACT_APP_PAYPAL_CLIENT_ID=$REACT_APP_PAYPAL_CLIENT_ID
ENV REACT_APP_PAYPAL_CLIENT_ID_SANDBOX=$REACT_APP_PAYPAL_CLIENT_ID_SANDBOX
ENV REACT_APP_PAYPAL_ENVIRONMENT=$REACT_APP_PAYPAL_ENVIRONMENT
ENV REACT_APP_PAYPAL_CURRENCY=$REACT_APP_PAYPAL_CURRENCY
ENV REACT_APP_PAYPAL_INTENT=$REACT_APP_PAYPAL_INTENT
ENV REACT_APP_EMAILJS_SERVICE_ID=$REACT_APP_EMAILJS_SERVICE_ID
ENV REACT_APP_EMAILJS_TEMPLATE_ID=$REACT_APP_EMAILJS_TEMPLATE_ID
ENV REACT_APP_EMAILJS_PUBLIC_KEY=$REACT_APP_EMAILJS_PUBLIC_KEY
ENV REACT_APP_TRANSLATE_API_KEY=$REACT_APP_TRANSLATE_API_KEY
ENV REACT_APP_STRIPE_PUBLISHABLE_KEY=$REACT_APP_STRIPE_PUBLISHABLE_KEY
ENV REACT_APP_FIREBASE_API_KEY=$REACT_APP_FIREBASE_API_KEY
ENV REACT_APP_FIREBASE_AUTH_DOMAIN=$REACT_APP_FIREBASE_AUTH_DOMAIN
ENV REACT_APP_FIREBASE_PROJECT_ID=$REACT_APP_FIREBASE_PROJECT_ID
ENV REACT_APP_FIREBASE_STORAGE_BUCKET=$REACT_APP_FIREBASE_STORAGE_BUCKET
ENV REACT_APP_FIREBASE_MESSAGING_SENDER_ID=$REACT_APP_FIREBASE_MESSAGING_SENDER_ID
ENV REACT_APP_FIREBASE_APP_ID=$REACT_APP_FIREBASE_APP_ID
ENV REACT_APP_SHIPPO_API_TOKEN=$REACT_APP_SHIPPO_API_TOKEN

# Build React app (set GENERATE_SOURCEMAP=false to reduce build size)
ENV GENERATE_SOURCEMAP=false
RUN npm run build

# Production stage
FROM node:18-alpine AS production

WORKDIR /app

# Copy package files
COPY package*.json ./

# Install only production dependencies
RUN npm ci --only=production

# Copy built app from builder
COPY --from=builder /app/build ./build

# Copy server files and necessary config files
COPY server.js ./
COPY start-railway.js ./
COPY craco.config.js ./
COPY postcss.config.js ./
COPY tailwind.config.js ./

# Expose port
EXPOSE 5000

# Health check
HEALTHCHECK --interval=30s --timeout=3s --start-period=40s --retries=3 \
  CMD node -e "require('http').get('http://localhost:5000/health', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"

# Start server
CMD ["node", "server.js"]

