[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npm run build"]
# Ensure REACT_APP_* variables are available during build

[start]
cmd = "npm run server"

