[build]
builder = "NIXPACKS"

[deploy]
startCommand = "node start-production.js"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.variables]
CI = "false"
